name: Build and Sign APK
on:
  push:
    branches:
      - main

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11.x
          
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
