name: Build Android

on: [push, pull_request]

jobs:
    build:
        name: Build APK
        runs-on: beevelop/ionic:latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v2
              
            - name: yarn install
              run: yarn install
