name: Build Android

on: [push, pull_request]

jobs:
    build:
        name: Build APK
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v3
        
            - name: Setup java
              uses: actions/setup-java@v3
              with:
                java-version: 11.x
        
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 13.x
